// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travelo.Infrastracture.Contexts;

#nullable disable

namespace Travelo.Infrastracture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel (ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");

                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("Roles");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.Payment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<DateTime>("PaymentDate").HasColumnType("datetime2");
                b.Property<string>("PaymentId").HasColumnType("nvarchar(max)");
                b.Property<int>("HotelId").HasColumnType("int");
                b.Property<int>("RoomId").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");

                b.HasKey("Id");
                b.HasIndex("HotelId");
                b.HasIndex("RoomId");
                b.HasIndex("UserId");

                b.ToTable("Payments");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.Restaurant", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("CityId").HasColumnType("int");
                b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("CityId");
                b.HasIndex("UserId").IsUnique().HasFilter("[UserId] IS NOT NULL");

                b.ToTable("Restaurants");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.Review", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");

                b.Property<decimal?>("AmenityRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal?>("CleanlinessRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal?>("CommunicationRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal?>("LocationRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal>("OverallRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<decimal?>("ValueRating").HasPrecision(18, 2).HasColumnType("decimal(18,2)");

                b.Property<string>("Comment").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<int>("HotelId").HasColumnType("int");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");

                b.HasKey("Id");
                b.HasIndex("HotelId");
                b.HasIndex("UserId");

                b.ToTable("Reviews");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.Payment", b =>
            {
                b.HasOne("Travelo.Domain.Models.Entities.Hotel", "Hotel")
                    .WithMany()
                    .HasForeignKey("HotelId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Travelo.Domain.Models.Entities.Room", "Room")
                    .WithMany()
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Travelo.Domain.Models.Entities.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Hotel");
                b.Navigation("Room");
                b.Navigation("User");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.Restaurant", b =>
            {
                b.HasOne("Travelo.Domain.Models.Entities.City", "City")
                    .WithMany("Restaurants")
                    .HasForeignKey("CityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Travelo.Domain.Models.Entities.ApplicationUser", "User")
                    .WithOne("Restaurant")
                    .HasForeignKey("Travelo.Domain.Models.Entities.Restaurant", "UserId");

                b.Navigation("City");
                b.Navigation("User");
            });

            modelBuilder.Entity("Travelo.Domain.Models.Entities.ApplicationUser", b =>
            {
                b.Navigation("Hotel");
                b.Navigation("Restaurant");
                b.Navigation("Reviews");
            });
#pragma warning restore 612, 618
        }
    }
}